### PR TITLE
Update actions/github-script to version 3.1.0

### PR DESCRIPTION
**Pull request by luck3y**

### CODE REVIEW

**Comment by luck3y** [comment]
@yersan @kabir FYI

**Comment by luck3y** [comment]
This failed previously with:

```
2020-12-10T21:07:55.8134087Z 2020-12-10 21:07:55,813 - root - ERROR - I1210 21:07:55.812610   26822 sti.go:711] [WARNING] The requested profile "openshift" could not be activated because it does not exist.
2020-12-10T21:07:55.8163055Z 2020-12-10 21:07:55,815 - root - ERROR - I1210 21:07:55.815205   26822 sti.go:711] [ERROR] Failed to execute goal org.jboss.galleon:galleon-maven-plugin:4.2.6.Final:provision-file (provision a provisioning.xml file) on project generic-provisioning: Provisioning failed: Failed to resolve Maven universe org.jboss.universe:community-universe: Failed to determine the latest version of org.jboss.universe:community-universe:jar:[0.0,). Make sure the remote Maven repository is properly configured and available. -> [Help 1]
2020-12-10T21:07:55.8167266Z 2020-12-10 21:07:55,816 - root - ERROR - I1210 21:07:55.815793   26822 sti.go:711] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jboss.galleon:galleon-maven-plugin:4.2.6.Final:provision-file (provision a provisioning.xml file) on project generic-provisioning: Provisioning failed
2020-12-10T21:07:55.8179619Z 2020-12-10 21:07:55,817 - root - ERROR - I1210 21:07:55.817068   26822 sti.go:711] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
2020-12-10T21:07:55.8183176Z 2020-12-10 21:07:55,817 - root - ERROR - I1210 21:07:55.817171   26822 sti.go:711] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
2020-12-10T21:07:55.8185602Z 2020-12-10 21:07:55,817 - root - ERROR - I1210 21:07:55.817267   26822 sti.go:711] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
2020-12-10T21:07:55.8188566Z 2020-12-10 21:07:55,817 - root - ERROR - I1210 21:07:55.817410   26822 sti.go:711] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
2020-12-10T21:07:55.8198565Z 2020-12-10 21:07:55,819 - root - ERROR - I1210 21:07:55.819105   26822 sti.go:711] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
2020-12-10T21:07:55.8277586Z 2020-12-10 21:07:55,819 - root - ERROR - I1210 21:07:55.819451   26822 sti.go:711] at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
2020-12-10T21:07:55.8288813Z 2020-12-10 21:07:55,819 - root - ERROR - I1210 21:07:55.819459   26822 sti.go:711] at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
2020-12-10T21:07:55.8291147Z 2020-12-10 21:07:55,820 - root - ERROR - I1210 21:07:55.819463   26822 sti.go:711] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
2020-12-10T21:07:55.8292962Z 2020-12-10 21:07:55,820 - root - ERROR - I1210 21:07:55.820173   26822 sti.go:711] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
2020-12-10T21:07:55.8294648Z 2020-12-10 21:07:55,820 - root - ERROR - I1210 21:07:55.820283   26822 sti.go:711] at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
2020-12-10T21:07:55.8296227Z 2020-12-10 21:07:55,820 - root - ERROR - I1210 21:07:55.820365   26822 sti.go:711] at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
2020-12-10T21:07:55.8297763Z 2020-12-10 21:07:55,821 - root - ERROR - I1210 21:07:55.820437   26822 sti.go:711] at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
2020-12-10T21:07:55.8299218Z 2020-12-10 21:07:55,821 - root - ERROR - I1210 21:07:55.820509   26822 sti.go:711] at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
2020-12-10T21:07:55.8301083Z 2020-12-10 21:07:55,821 - root - ERROR - I1210 21:07:55.820644   26822 sti.go:711] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-12-10T21:07:55.8304425Z 2020-12-10 21:07:55,821 - root - ERROR - I1210 21:07:55.820777   26822 sti.go:711] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-12-10T21:07:55.8307315Z 2020-12-10 21:07:55,822 - root - ERROR - I1210 21:07:55.820781   26822 sti.go:711] at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-12-10T21:07:55.8309489Z 2020-12-10 21:07:55,822 - root - ERROR - I1210 21:07:55.820882   26822 sti.go:711] at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2020-12-10T21:07:55.8311568Z 2020-12-10 21:07:55,822 - root - ERROR - I1210 21:07:55.820984   26822 sti.go:711] at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
2020-12-10T21:07:55.8314625Z 2020-12-10 21:07:55,822 - root - ERROR - I1210 21:07:55.821260   26822 sti.go:711] at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
2020-12-10T21:07:55.8317242Z 2020-12-10 21:07:55,823 - root - ERROR - I1210 21:07:55.821264   26822 sti.go:711] at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
2020-12-10T21:07:55.8319787Z 2020-12-10 21:07:55,823 - root - ERROR - I1210 21:07:55.821268   26822 sti.go:711] at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
2020-12-10T21:07:55.8321890Z 2020-12-10 21:07:55,823 - root - ERROR - I1210 21:07:55.821272   26822 sti.go:711] Caused by: org.apache.maven.plugin.MojoExecutionException: Provisioning failed
2020-12-10T21:07:55.8324338Z 2020-12-10 21:07:55,823 - root - ERROR - I1210 21:07:55.821413   26822 sti.go:711] at org.jboss.galleon.maven.plugin.ProvisionFileStateMojo.execute(ProvisionFileStateMojo.java:122)
2020-12-10T21:07:55.8327355Z 2020-12-10 21:07:55,824 - root - ERROR - I1210 21:07:55.821516   26822 sti.go:711] at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
2020-12-10T21:07:55.8330066Z 2020-12-10 21:07:55,824 - root - ERROR - I1210 21:07:55.821627   26822 sti.go:711] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
2020-12-10T21:07:55.8331595Z 2020-12-10 21:07:55,824 - root - ERROR - I1210 21:07:55.821748   26822 sti.go:711] ... 20 more
2020-12-10T21:07:55.8333879Z 2020-12-10 21:07:55,824 - root - ERROR - I1210 21:07:55.822065   26822 sti.go:711] Caused by: org.jboss.galleon.universe.maven.MavenUniverseException: Failed to resolve Maven universe org.jboss.universe:community-universe
2020-12-10T21:07:55.8337040Z 2020-12-10 21:07:55,824 - root - ERROR - I1210 21:07:55.822165   26822 sti.go:711] at org.jboss.galleon.universe.maven.MavenUniverseFactory.getUniverse(MavenUniverseFactory.java:65)
2020-12-10T21:07:55.8339994Z 2020-12-10 21:07:55,825 - root - ERROR - I1210 21:07:55.822263   26822 sti.go:711] at org.jboss.galleon.universe.UniverseFactoryLoader.getUniverse(UniverseFactoryLoader.java:110)
2020-12-10T21:07:55.8342645Z 2020-12-10 21:07:55,825 - root - ERROR - I1210 21:07:55.822451   26822 sti.go:711] at org.jboss.galleon.universe.UniverseResolver.getUniverse(UniverseResolver.java:87)
2020-12-10T21:07:55.8345191Z 2020-12-10 21:07:55,825 - root - ERROR - I1210 21:07:55.822627   26822 sti.go:711] at org.jboss.galleon.universe.UniverseResolver.getUniverse(UniverseResolver.java:81)
2020-12-10T21:07:55.8347536Z 2020-12-10 21:07:55,825 - root - ERROR - I1210 21:07:55.822632   26822 sti.go:711] at org.jboss.galleon.universe.UniverseResolver.resolve(UniverseResolver.java:124)
2020-12-10T21:07:55.8350511Z 2020-12-10 21:07:55,825 - root - ERROR - I1210 21:07:55.822636   26822 sti.go:711] at org.jboss.galleon.layout.ProvisioningLayoutFactory.resolveFeaturePackDir(ProvisioningLayoutFactory.java:207)
2020-12-10T21:07:55.8356024Z 2020-12-10 21:07:55,825 - root - ERROR - I1210 21:07:55.822727   26822 sti.go:711] at org.jboss.galleon.layout.ProvisioningLayoutFactory.resolveFeaturePack(ProvisioningLayoutFactory.java:180)
2020-12-10T21:07:55.8365739Z 2020-12-10 21:07:55,826 - root - ERROR - I1210 21:07:55.822828   26822 sti.go:711] at org.jboss.galleon.layout.ProvisioningLayout.resolveFeaturePack(ProvisioningLayout.java:1152)
2020-12-10T21:07:55.8369514Z 2020-12-10 21:07:55,826 - root - ERROR - I1210 21:07:55.822923   26822 sti.go:711] at org.jboss.galleon.layout.ProvisioningLayout.layout(ProvisioningLayout.java:1088)
2020-12-10T21:07:55.8378267Z 2020-12-10 21:07:55,826 - root - ERROR - I1210 21:07:55.822994   26822 sti.go:711] at org.jboss.galleon.layout.ProvisioningLayout.doBuild(ProvisioningLayout.java:895)
2020-12-10T21:07:55.8380687Z 2020-12-10 21:07:55,826 - root - ERROR - I1210 21:07:55.823093   26822 sti.go:711] at org.jboss.galleon.layout.ProvisioningLayout.build(ProvisioningLayout.java:883)
2020-12-10T21:07:55.8382937Z 2020-12-10 21:07:55,826 - root - ERROR - I1210 21:07:55.823184   26822 sti.go:711] at org.jboss.galleon.layout.ProvisioningLayout.<init>(ProvisioningLayout.java:370)
2020-12-10T21:07:55.8385630Z 2020-12-10 21:07:55,826 - root - ERROR - I1210 21:07:55.823269   26822 sti.go:711] at org.jboss.galleon.layout.ProvisioningLayoutFactory.newConfigLayout(ProvisioningLayoutFactory.java:175)
2020-12-10T21:07:55.8388480Z 2020-12-10 21:07:55,827 - root - ERROR - I1210 21:07:55.823428   26822 sti.go:711] at org.jboss.galleon.ProvisioningManager.newConfigLayout(ProvisioningManager.java:615)
2020-12-10T21:07:55.8390774Z 2020-12-10 21:07:55,827 - root - ERROR - I1210 21:07:55.823436   26822 sti.go:711] at org.jboss.galleon.ProvisioningManager.provision(ProvisioningManager.java:437)
2020-12-10T21:07:55.8393999Z 2020-12-10 21:07:55,827 - root - ERROR - I1210 21:07:55.823526   26822 sti.go:711] at org.jboss.galleon.maven.plugin.ProvisionFileStateMojo.doProvision(ProvisionFileStateMojo.java:139)
2020-12-10T21:07:55.8397091Z 2020-12-10 21:07:55,827 - root - ERROR - I1210 21:07:55.823821   26822 sti.go:711] at org.jboss.galleon.maven.plugin.ProvisionFileStateMojo.execute(ProvisionFileStateMojo.java:120)
2020-12-10T21:07:55.8398889Z 2020-12-10 21:07:55,827 - root - ERROR - I1210 21:07:55.823826   26822 sti.go:711] ... 22 more
2020-12-10T21:07:55.8401586Z 2020-12-10 21:07:55,827 - root - ERROR - I1210 21:07:55.823830   26822 sti.go:711] Caused by: org.jboss.galleon.universe.maven.MavenLatestVersionNotAvailableException: Failed to determine the latest version of org.jboss.universe:community-universe:jar:[0.0,). Make sure the remote Maven repository is properly configured and available.
2020-12-10T21:07:55.8406787Z 2020-12-10 21:07:55,828 - root - ERROR - I1210 21:07:55.823970   26822 sti.go:711] at org.jboss.galleon.maven.plugin.util.AbstractMavenArtifactRepositoryManager.doGetHighestVersion(AbstractMavenArtifactRepositoryManager.java:139)
2020-12-10T21:07:55.8412517Z 2020-12-10 21:07:55,828 - root - ERROR - I1210 21:07:55.824237   26822 sti.go:711] at org.jboss.galleon.maven.plugin.util.AbstractMavenArtifactRepositoryManager.resolveLatestVersion(AbstractMavenArtifactRepositoryManager.java:111)

**Comment by luck3y** [comment]
```
2020-12-10T21:14:26.6270640Z [31m2020-12-10 21:14:26,625 cekit        ERROR    Test execution failed, please consult output above
2020-12-10T21:14:26.6272375Z Traceback (most recent call last):
2020-12-10T21:14:26.6272736Z 
2020-12-10T21:14:26.6273073Z Failing scenarios:
2020-12-10T21:14:26.6274221Z   features/wildfly-s2i-modules/s2i.feature:297  Test galleon and app build, download of artifacts
2020-12-10T21:14:26.6275465Z   features/wildfly-s2i-modules/s2i.feature:301  Test galleon and app incremental build, no download of artifacts
2020-12-10T21:14:26.6276631Z   features/wildfly-s2i-modules/s2i.feature:305  Test galleon build, download of artifacts
2020-12-10T21:14:26.6277826Z   features/wildfly-s2i-modules/s2i.feature:309  Test galleon incremental build, no download of artifacts

**Comment by luck3y** [comment]
@jfdenise Any idea on the maven failure? Looks odd to me.
```
2020-12-10T21:07:55.8163055Z 2020-12-10 21:07:55,815 - root - ERROR - I1210 21:07:55.815205   26822 sti.go:711] [ERROR] Failed to execute goal org.jboss.galleon:galleon-maven-plugin:4.2.6.Final:provision-file (provision a provisioning.xml file) on project generic-provisioning: Provisioning failed: Failed to resolve Maven universe org.jboss.universe:community-universe: Failed to determine the latest version of org.jboss.universe:community-universe:jar:[0.0,). Make sure the remote Maven repository is properly configured and available. -> [Help 1]

**Comment by jfdenise** [comment]
From the trace it seems maven repo not being accessible. I am re-running the job.

**Comment by jfdenise** [comment]
@luck3y it failed again, that is a real problem unrelated to your changes. The testcase accesses directly to the WildFly FP (not the s2i one) and the universe is not found in the repositories (central). It is only in nexus. This bugged me since some time, I suspect that it is because it is in org.jboss GroupId. I need to ask about that and release the universe in central if we can.
 
It has been introduced by : https://issues.redhat.com/browse/CLOUD-3847. We are no more taking into account MAVEN_ARGS_APPEND, this can break galleon provisioning.
It was hidden because to fix https://issues.redhat.com/browse/CLOUD-3647, https://github.com/wildfly/wildfly-s2i/commit/dcae25b6b142892a4880d5cb16e043b191a671ee
we set this env variable, and galleon was benefiting from it.

I am looking at what would be the best fix once the nexus vs central issue is understood.

**Review by jfdenise — APPROVED** [review]

**Pull request merged**
