### PR TITLE
CLOUD-3629 - Add github actions CI for wildfly-s2i

### PR DESCRIPTION
**Pull request by luck3y**
https://issues.redhat.com/browse/CLOUD-3629
Signed-off-by: Ken Wills <kwills@redhat.com>

### CODE REVIEW

**Comment by luck3y** [comment]
Follows up on https://github.com/wildfly/wildfly-s2i/pull/101

@jfdenise This runs the additional tests as well, thanks for pointing those out.

Note the push to quay.io likely won't work due to PRs not being allowed to access secrets, which there appears to be a workaround for, but I'll add that as a separate change.

When this is merged and you rebase your own forks, setting QUAY_REPO, QUAY_USERNAME and QUAY_PASSWORD will allow you to push to the CI repo set up in quay (I'll mail this info out for the shared repo.)

**Comment by luck3y** [comment]
Tests passed here: https://github.com/luck3y/wildfly-s2i/runs/740817299?check_suite_focus=true

**Comment by luck3y** [comment]
Also see: https://github.com/cekit/behave-test-steps/pull/28

**Comment by jmesnil** [comment]
@luck3y Thanks.

Fiy, I've merged it as it is but next time, let's use the WFLY issue tracker and the OpenShift component to track work on wildfly-s2i. (I've cloned this issue to https://issues.redhat.com/browse/WFLY-13574 after it was merged)

**Pull request merged**
