### PR TITLE
[CLOUD-3470] Add behave tests for jpa-dist and ejb-dist-cache

### PR DESCRIPTION
**Pull request by yersan**
Add behave tests to verify `jpa-dist` and `ejb-dist-cache` Galleon layers

Jira issue: https://issues.redhat.com/browse/CLOUD-3470
Requires: https://github.com/wildfly/wildfly-s2i/pull/128

### CODE REVIEW

**Comment by yersan** [comment]
Hello @luck3y , there was an error with the CI job, do you have any clue about the reasons? It seems to be a configuration issue.

**Comment by yersan** [comment]
Hi @luck3y and maybe @kabir , do you have any idea why is the CI failing with such a message?

**Comment by kabir** [comment]
@yersan ::set-env in GitHub Actions was deprecated for a while and has now been removed. The new way is to write the name, value pairs to $GITHUB-ENV. Here is an [example](https://github.com/kabir/wildfly/blob/reactive-port-with-gh-actions/.github/workflows/reactive-port-against-feature-pack.yml#L68).

I don't see any direct usage of this in your .github/workflows/*.yml files - but it seems to be the actions/github-script@0.3.0 that is failing. I guess you need to update that to a newer version (latest seems to be 3.1.0)

**Comment by luck3y** [comment]
@yersan Sorry I just saw this, and I was out on PTO last week, I'll open a PR for this today. (Also, thanks @kabir!)

**Comment by luck3y** [comment]
I opened: https://github.com/wildfly/wildfly-s2i/pull/125 for this.

**Comment by jfdenise** [comment]
@yersan , yo ucan rebase your PR, we have the correct version now.

**Comment by yersan** [comment]
Thank you @luck3y @kabir @jfdenise for the help. I filled https://github.com/wildfly/wildfly-s2i/pull/128 which should we merged first before this one.

I'll force push again once #128 is in place

**Comment by jfdenise** [comment]
@yersan , other pr merged.

**Pull request merged**
