### PR TITLE
Use community version of jolokia

### PR DESCRIPTION
**Pull request by luck3y**
https://github.com/jboss-openshift/cct_module/pull/355
Signed-off-by: Ken Wills <kwills@redhat.com>

### CODE REVIEW

**Comment by luck3y** [comment]
Requires: https://github.com/jboss-openshift/cct_module/pull/355

**Comment by luck3y** [comment]
@jfdenise This works fine with 0.37.1 branch of cct_module, but I didn't include that upgrade here, let me know if you want it as part of this and I'll add it.

**Comment by jfdenise** [comment]
@luck3y +1 for 0.37.1

**Comment by luck3y** [comment]
@jfdenise Added the move to cct_module 0.37.1 and squashed.

**Comment by jfdenise** [comment]
@luck3y thanks, merged.

**Pull request merged**
